# Fake PVC for single-node installs
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hub-db-dir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
